sudo: false
language: node_js
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
node_js:
- '4'
before_install:
- npm i -g npm@^2.0.0
before_script:
- npm prune
script:
- npm run test:ci
- npm run check-coverage
after_success:
- npm run report-coverage
- npm run semantic-release
env:
  global:
  - secure: egmZYSjqp6I4MOy4AFEGI6ddTSu9hwRoEaxQValsVjKEgK4FuArX9NrAvQkJtOkvJ59CSHGk4N3IQkAxBeOyy3UfE1NRvqg54kDlJHSLxHzvTKGLMhWNIvHeQ5mxcnQE57JcX9RyCQIYdf7+ypAoSabxJT/gCTPQAHVGtZGW0JQ0POWEvRh2kpDImQ3347wL0VY35ruC3+wZSpi3TJyqk+LnXgp9StHZ88+zhyQ8iVpmKVVOdTcjklzK+LiruTGiiUkGsPPGaWAGTiY81NiZPg5j+buyPhJz7iQsAhr1mXz6SA/PDMFvPSvqyK4APYMBVg+6JGUQ9vCLjMI1+S9sl9F9gRpgjPWqUPc8vets8JGZNupk/mRWxruqZ99d/LiYOGGdXqZQX9DpgZezds/t5Gzsj2BGsBgHpq5PSh4cdhVi6fjXOuN/ZfDHbY/ostvF7nlWthgFCxKpZN2mL2+BcYitwxP9LiGnvN1aEG6+jmOCsDZ3j2Zul0ObVFqmrmIjjbisM0KSsfRMzyUoXoum76Czes13eZbfEUGZwOeHICzG/6Rucw6cackUt0So35hrrmnr84rFlTksAw7looJ5aK0PZNAYgC8laNT1V9FiEDgtLyewbyo6WJkLuSkwumyaMiQbt6Ugf8xxqTNv4Nf4mtxq3U5rn8M8U01/ArN0Udg=
  - secure: GMnsVBtaNyn33BxDO2IsopGybzI9Vgx6Wk1tLQyGmD7d+xTbghO82z4VSxmwR8Een2yYa2UXyjZE0IY/vGWuDjmL+sWu6CICUyLYq4jHIThMeJm5YxdceAYGiDBZQAwB+MvhEko95V4UdpDEfzOZH9KCeJ/cBM8rTY3LPIuAtqZq7m870Cb/54ZAmnvIMppyRzYk/6QSXmgLH50gGHetLxR0brtD+0D6cGOHJ+E4E/Gj+c8DZvwduK8TW6b82x+dp3kuNCyRgcHkeMbB7fNzXguhC8OeLxf6ulfol1Qi3cImG4Ut4JpmXw39iF6LwHARi4vRCSXN4Kor/BumMREZKw7W1qB6CA1A8nu33LAoOeSoSi0aUwMVXxDeylKounL6+MoJDwD0VX+NlP+mtTRFNXwrJ2WgmqHrUcMRUlVEq4RXk8//10upUeo5X3nkqLlrP0B0X0qiTug3bPJK+61FUcFjFPtvsxJ3mO/g6BlqsOhejRJxmHdxdvka4uxJlJ1SC4robm2YeAqH79mu9Fcg/7k9DRk3pnsEhes4mjCxpgX5HF6TMcwNOEQytksJ4qhdsZdQOMsKDJQOn6kY6JEn0Q4wEKxT1SJlXrPyPYG12C9B7uwwMhAD31nxYGqMPzBzW8xLJxmM9kyr+GLMoOJlgJNCg/pH9DE31neo5cqglg0=
  - secure: NNguASwZFv5Xc04oNwkhMjYAvTxfo9NgH2IgMHXX1yuDEVkgjg/YEpMK6ktwcFAWxtANA220wPhCBOYuYd4GM1hdvjtn0EKSkys/Vhzwyj1cpIqijIaYZDyfTXgUh/c/MgIxwstzo7DRh7iCEPuJGGhXT5u68P3XMxFb9gdq/YL7vPHY2wXXniO7n6CxUbcAMpBJoVOlkw7DSG515HWpzXaph2VwYaNVRUGRX26MBQApy5q0OELFEr3z+bk2y6Flcb39ALQDBDpFRvfD15bAbF1/Yog/ZioSGcmxUfDLzS64ijEb2hzJmo+vwL54Hw3+F8OM0SOJ46uoZMqeWbmmfRVVE5q6r0xfuOMSAmzlaD7J3+HZQ+CY8P+Y2KH719ZXDSL+XcK9i1zQeoJO5tlFiRpHELQEo2kmpCKyg2TChTIBpLvBcB4iSbJ5q6Wck0nF7glxeurJM7l9jUeu4AapDFHsjVEBqMrWDHQ6BXsfq+9BrG5ePkjh8K2YHwjUHzH88gsQpGwUyQmhnEGLabWylauoCY1K+bdolOptoPe9XC4vUofyUw2KUC08VQS92xbkZPvumkB6yUyBEwVyQ6ZaA660/+++TGDuhupzGRiEeg0vaz9+X1MivoXLWWTDsJzSR7yfKPunIVhZBwKH++dtFrfmnMMwo5QJnJS9VCH3vFE=
