sudo: false
language: node_js
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
node_js:
- '4'
before_install:
- npm i -g npm@^2.0.0
install:
- npm install -g codecov
before_script:
- npm prune
script:
- npm run test:ci
- npm run check-coverage
after_success:
- npm run report-coverage
- npm run semantic-release
- codecov
env:
  global:
  - secure: hw2WjzNl772jeGRgnbZDMH6d9/+LcDPvuKP5U0OqtvFFxmX2hGSDe3L0s/XZJDRf4HfKbyzmyn9oHQPDfKvxxUOiHsNlTvtYVu50XLg+LHTK1RwYVGFF3k0ZlzeGSBzlhg2yv0PoZpExPmkb3b3zCT5Xr9O4lro/K7eDZj6Iji+3uia07FyeDYHr7BafierxJqkGcLhVOXfws2XGgnes9WL3+axPtNI+dc5WCcq79OFeqQtMu+VWZCkzseZL9SBvFUWUuJGoY1iiqYla8jA/lkD660lSTr40IeRirDK5Pwk9h9OQ8xqxQ1rJr94ILDbdhqIEMPcrmKNdPrk/SSYbztFqZZLzYXZ9uHXx/w2Bym50zAQuIRoKrBfRe+ihrzIDCHPOponhbvyyorgMN+4c4FO7kVqn8jeYfmV6RLRc9pWB2eaLvI0tDwksFgU0VnIrxJf/CxYQNxL9YwoMi1LSjEhCTIYjdIu5kZ791R8eSyVFD3SKDpMcZRZn+giTKXJXDIBUHf6694xqemNQ705/ZkPa9bmgsdZ7SXO+FCe8LfN7olfV7ZwtcnJYIMPnHx4HlD3vuErNVk4A9nPfkC4xLuJHQgnOgMwLqrmDZS4Rgm0CeX0EExv2IHXS2z+6Ct6BZQ13aW6DtAmWBeUbsdAD2QFby7wdsmFMetgzja5KL1I=
  - secure: mB7gOw5AzfFKTMw28TuB2+Vt0zDq2wI76/IbZP+4Ej+iGoFnPql9Bzc1j/14sWIICtV/hKvfgIxuRQQy01p4bB4xcgnvWjiAxTE8hUWqt6ph5mDXc7+YefWAR9YXyQTTwW3OXyWy3kImqPs+X6hBuwfUWnnb2nr0mgnYPHfdsSyPygVjz8hbhCkExDWnIYeP02dVjSF2hXlQlQ120410FdlTt/92X/G1UhkZUZdbgcfIjujSbJXUjvoaF1YoLgf6LdT9jRg/GnJmIibOud04Aly4QKy2ABfifEbtbjziAVr5Jbz3LP4qQfGG4KAjlEy1Q2XB2xLLObFhXW+6Z483Kz+oGyLUcWAkXyEm0T5vYU3twUN4mG4LJ0yCInCZXG9Aj+6O2d8udUEl/KOA+Zx8aBnwSsiULplY6DWmS3/2rHi4cqSX7ZD2HPgT4tVuFV/VPhRHsuhzpKw1AaDVzwoTnqEvAwErupihHkLVZp4CmiiOnLUY8GDMCOMfGbRomLjGnC3cTkLVHafWPpCCfJ+9C3mVjaREDi7Xu9LbMmPO7FkzKZ+oiEiMt2jCD/39Dyrwv6iZ+Om+KcCJsnmKZfZ2y+6gI6uBsac4Z9pDm9OsKlRFTeKGW65hJBmCL6yVJSNkQFeV4yTrfWey4Rqwo9CHejr2THtTQjnQ398yLjbQcP8=
  - secure: VDEsZFkte/vHxyXA/H10EIVQsr97eA9TjtcpbgGlR/hlklsxWVEwX9Y9KSQQ/mWI9+MNC/V1aPVGjlfgg+tIeZsP6DpBOcTHOXvqXBv5+Y8c92GDIJFEdmhNjAiqmyuvnfqHC+S4DHGzoJ3AFvcH4aI6BpZGBwrd8eOWPM0W6XE5aEnXRHa36CCUOC2JoPM/iv4ioUiFlO2dGJw8O9aXouIVf8Kd1s5x1r6qxpTAbx/x3XXEaSh4q8Yd4T38r1Xy+ikFCZAjgKMqMRmDsU+iOJzf6PsmvnnzCSJIhc0x3Zf5VQk+4xC0uAaJyv9XsKyu6W//qWS98/+OSCDLi1NL51PFvHcehagz2U/G6z7VCdxbLzJOuLG5goEu3+j9F/PS9knW2zxj3lRj5i7MHag/A7KThwuNZFQh/FlaVl739HInjIx/AQ2SMM6h5wDARkOIa6kRX+QRDxoh9Req9a4hi7x8/LyDPwuFX/J7h6GDFWyQxt2MHYyOiy6t9y2KTSTh/7JQgm9g4FgYgRB5wfX+DV2ctI11Dv2r4McFsQDBMAH2drFTnCIazgrozkr8XDI9QKKbWp0QrQ9eaoiGUz6fiYyRI4vtiNxnrmkWwRLiWNNm7kznKUz8Sm+XTe34cFZsLAFCH+l8f3FkFI17RwhDcQvpgg3eiU/C1IiXmxfTNbo=
